# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-08-10 14:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Log',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField()),
                ('level', models.CharField(max_length=50)),
                ('message', models.TextField()),
                ('name_logger', models.CharField(max_length=100)),
                ('sender', models.CharField(max_length=100)),
            ],
        ),
    ]
